language: scala
scala:
   - 2.11.2
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y git
  - git clone https://github.com/scalatra/scalatra-website.git
  - git clone https://github.com/scalatra/scalatra.git
script: hello.sh
