language: scala
scala:
   - 2.11.2
jdk:
  - oraclejdk8
env:
  global:
  - ENCRYPTION_LABEL: "abeef26245c2"
before_install:
  - git clone https://github.com/scalatra/scalatra-website.git
  - git clone https://github.com/scalatra/scalatra.git
script: ./hello.sh
